### ISSUE TITLE
 problems about runDisort_mat

### ISSUE THREAD

**Issue by Wangshuaibozju** [prowe12/runDisort_mat#1]
The matlab wrapper（runDisort_mat）is a very convenient tool to use DISORT, and I have some problems in using it.

First, I notice these two file “pmom_water_T300_DW_S331.nc” and “pmom_ice_sphere_T266_Warren_S331.nc” are not provided in your github repository when I run the “sample_run.m” in matlab.

Second, the clrod for clear-sky optical depths (gases), and cloud properties are both included in the sample_run.m, however, the aerosol properties are seems not included.

So can you provide these two files ? and I am not sure if I make a mistake about the aerosol in the runDISORT_mat.

**Comment by prowe12** [comment]
Thank you for your interest. Regarding your questions:

1. The files are too large to include on GitHub, but I now provide links in the readme. Please let me know if you have any problems.
2. Unfortunately, I did not incorporate aerosols. You would need to add them on yourself.

Finally, please note that I am no longer upgrading this code because I have switched to running DISORT through Python. If possible, I recommend the Python version (runDisort_py).
